name: idea_maker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: 3.0.5

dependencies:
  app_review: ^2.1.2+1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dio: ^4.0.4
  enum_to_string: ^2.0.1
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_dynamic_links: ^4.3.3
  firebase_remote_config: ^2.0.13
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.18.0
  flutter_launcher_icons: ^0.9.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^1.0.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  retrofit: '>=3.0.0 <4.0.0'
  shared_preferences: ^2.0.8
  state_notifier: ^0.7.1
  webview_flutter: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_gen_runner: ^4.1.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  json_serializable: ^6.0.1
  pedantic_mono: any
  retrofit_generator: ^4.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true

fonts:
  - family: NotoSansJP
    fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.otf
        weight: 400
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.otf
        weight: 500
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.otf
        weight: 700    
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700