// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9WxLMOniF1nMNHVw-vEsK9dZVjGWXFI',
    appId: '1:32269245189:web:bd9013609234e1ac46f56c',
    messagingSenderId: '32269245189',
    projectId: 'learning-b9864',
    authDomain: 'learning-b9864.firebaseapp.com',
    storageBucket: 'learning-b9864.appspot.com',
    measurementId: 'G-TYH0L2M3JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFMFNoCDyXF_5a-vgagOEf9FFzj6wHoE',
    appId: '1:32269245189:android:dc498651b427150146f56c',
    messagingSenderId: '32269245189',
    projectId: 'learning-b9864',
    storageBucket: 'learning-b9864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZvJgHQVtldjoI1dWFLUxuusuy6stRUQ',
    appId: '1:32269245189:ios:e686e00ad88056b746f56c',
    messagingSenderId: '32269245189',
    projectId: 'learning-b9864',
    storageBucket: 'learning-b9864.appspot.com',
    iosClientId:
        '32269245189-vk8jl475p1h69rb23u6ikt7l8uhrkqtd.apps.googleusercontent.com',
    iosBundleId: 'yuskey38.ideaMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqZvJgHQVtldjoI1dWFLUxuusuy6stRUQ',
    appId: '1:32269245189:ios:e686e00ad88056b746f56c',
    messagingSenderId: '32269245189',
    projectId: 'learning-b9864',
    storageBucket: 'learning-b9864.appspot.com',
    iosClientId:
        '32269245189-vk8jl475p1h69rb23u6ikt7l8uhrkqtd.apps.googleusercontent.com',
    iosBundleId: 'yuskey38.ideaMaker',
  );
}
